// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/campaigns/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/campaigns/[id].get').default>>>>
    }
    '/api/campaigns/:id/pause': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/campaigns/[id]/pause.post').default>>>>
    }
    '/api/campaigns/:id/start': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/campaigns/[id]/start.post').default>>>>
    }
    '/api/campaigns/:id/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/campaigns/[id]/status.get').default>>>>
    }
    '/api/campaigns': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/campaigns/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/campaigns/index.post').default>>>>
    }
    '/api/contacts/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contacts/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contacts/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contacts/[id].put').default>>>>
    }
    '/api/contacts/bulk-delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contacts/bulk-delete.post').default>>>>
    }
    '/api/contacts/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contacts/import.post').default>>>>
    }
    '/api/contacts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contacts/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contacts/index.post').default>>>>
    }
    '/api/settings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/settings/index.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/settings/index.put').default>>>>
    }
    '/api/stats/dashboard': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats/dashboard.get').default>>>>
    }
    '/api/templates/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/templates/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/templates/[id].put').default>>>>
    }
    '/api/templates': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/templates/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/templates/index.post').default>>>>
    }
    '/api/whatsapp/disconnect': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/whatsapp/disconnect.post').default>>>>
    }
    '/api/whatsapp/qr': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/whatsapp/qr.get').default>>>>
    }
    '/api/whatsapp/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/whatsapp/status.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/_i18n/:hash/:locale/messages.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/i18n/dist/runtime/server/routes/messages').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}