// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 24/06/2026, 18:04:09
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/ema/Scrivania/altri repooo/wa-sender-pro/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ema/Scrivania/altri repooo/wa-sender-pro/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ema/Scrivania/altri repooo/wa-sender-pro/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ema/Scrivania/altri repooo/wa-sender-pro/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ema/Scrivania/altri repooo/wa-sender-pro/plugins/**/*.{js,ts,mjs}","/home/ema/Scrivania/altri repooo/wa-sender-pro/composables/**/*.{js,ts,mjs}","/home/ema/Scrivania/altri repooo/wa-sender-pro/utils/**/*.{js,ts,mjs}","/home/ema/Scrivania/altri repooo/wa-sender-pro/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ema/Scrivania/altri repooo/wa-sender-pro/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/ema/Scrivania/altri repooo/wa-sender-pro/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/ema/Scrivania/altri repooo/wa-sender-pro/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;